name: virtual_thrust
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - spiceypy
  - matplotlib
  - plotly
  - cvxpy
  - clarabel
  - ecos
  - scs
  - pytest
  - pip
  - pip:
      - Mosek
